# GitHub Action workflow file

name: FastLane Try Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-for-pr:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo "::notice::GitHub Action for Fastlane scan"
        echo "${{ github.actor }} is testing out GitHub Actions ğŸš€"
        echo â€œğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event.â€
        echo â€œğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!â€
        echo â€œğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.â€
        echo â€œğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner.â€
        echo â€œğŸ–¥ï¸ The workflow is now ready to test your code on the runner.â€
    - name: Run fastlane
      run: fastlane scan
    - name: Status message
      run: echo â€œğŸ This jobâ€™s status is ${{ job.status }}.â€
